// ========================================
// 初期データ：家族旅行のしおり
// アプリを初めて開いた時に自動でこのデータが入る
// ========================================

import { Trip } from './types';

export const SEED_TRIP: Trip = {
  id: 'trip-family-tokyo-2026',
  title: '家族旅行 東京・熱海・富士 2026',
  startDate: '2026-04-10',
  endDate: '2026-04-13',
  shareId: 'share-family-2026',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  days: [
    // ─── Day 1：広宣流布大誓堂、屋形船 ───
    {
      id: 'day-1',
      tripId: 'trip-family-tokyo-2026',
      dayNum: 1,
      headline: '広宣流布大誓堂、屋形船',
      spots: [
        {
          id: 'spot-1-1',
          dayId: 'day-1',
          name: '女満��空港（両親出発）',
          type: 'transit',
          isMain: false,
          time: '07:00',
          transport: 'subway',
          lat: 43.8808,
          lng: 144.1646,
          memo: '両親：女満別空港から羽田空港へ',
          sortOrder: 0,
        },
        {
          id: 'spot-1-2',
          dayId: 'day-1',
          name: '旭川空港（息子出発）',
          type: 'transit',
          isMain: false,
          time: '07:30',
          transport: 'subway',
          lat: 43.6708,
          lng: 142.4475,
          memo: '息子：旭川空港から羽田空港へ',
          sortOrder: 1,
        },
        {
          id: 'spot-1-3',
          dayId: 'day-1',
          name: '羽田空港（合流）',
          type: 'transit',
          isMain: false,
          time: '10:00',
          lat: 35.5494,
          lng: 139.7798,
          memo: '全員合流',
          sortOrder: 2,
        },
        {
          id: 'spot-1-4',
          dayId: 'day-1',
          name: '広宣流布大誓堂',
          type: 'destination',
          isMain: true,
          time: '12:00',
          endTime: '15:00',
          transport: 'subway',
          lat: 35.6997,
          lng: 139.7174,
          memo: '',
          sortOrder: 3,
        },
        {
          id: 'spot-1-5',
          dayId: 'day-1',
          name: 'ホテルXXX（両国）',
          type: 'hotel',
          isMain: false,
          time: '15:30',
          transport: 'subway',
          lat: 35.6954,
          lng: 139.7935,
          memo: 'チ��ックイン・荷物を置く',
          sortOrder: 4,
        },
        {
          id: 'spot-1-6',
          dayId: 'day-1',
          name: '屋形船（両国）',
          type: 'destination',
          isMain: true,
          time: '18:00',
          endTime: '20:30',
          transport: 'walk',
          lat: 35.6932,
          lng: 139.7945,
          memo: '両国から屋形船で夜景を楽しむ',
          sortOrder: 5,
        },
        {
          id: 'spot-1-7',
          dayId: 'day-1',
          name: 'ホテルXXX（両国）',
          type: 'hotel',
          isMain: false,
          time: '21:00',
          transport: 'walk',
          lat: 35.6954,
          lng: 139.7935,
          memo: '宿泊',
          sortOrder: 6,
        },
      ],
    },
    // ─── Day 2：創価大学、熱海ホテル ───
    {
      id: 'day-2',
      tripId: 'trip-family-tokyo-2026',
      dayNum: 2,
      headline: '創価大学、熱海ホテル',
      spots: [
        {
          id: 'spot-2-1',
          dayId: 'day-2',
          name: 'ホテルXXX（両国）',
          type: 'hotel',
          isMain: false,
          time: '08:00',
          transport: 'subway',
          lat: 35.6954,
          lng: 139.7935,
          memo: 'チェックアウト',
          sortOrder: 0,
        },
        {
          id: 'spot-2-2',
          dayId: 'day-2',
          name: '創価大学',
          type: 'destination',
          isMain: true,
          time: '10:00',
          endTime: '14:00',
          transport: 'subway',
          lat: 35.7310,
          lng: 139.3445,
          memo: '',
          sortOrder: 1,
        },
        {
          id: 'spot-2-3',
          dayId: 'day-2',
          name: '熱海ホテル',
          type: 'hotel',
          isMain: true,
          time: '17:00',
          transport: 'subway',
          lat: 35.0964,
          lng: 139.0714,
          memo: 'チェックイン・温泉',
          sortOrder: 2,
        },
      ],
    },
    // ─── Day 3：富士サファリパーク、五味八珍 ───
    {
      id: 'day-3',
      tripId: 'trip-family-tokyo-2026',
      dayNum: 3,
      headline: '富士サファリパーク、五味八珍',
      spots: [
        {
          id: 'spot-3-1',
          dayId: 'day-3',
          name: 'YYYホテル（三島）',
          type: 'hotel',
          isMain: false,
          time: '08:00',
          transport: 'taxi',
          lat: 35.1189,
          lng: 138.9111,
          memo: 'チェックアウト',
          sortOrder: 0,
        },
        {
          id: 'spot-3-2',
          dayId: 'day-3',
          name: '富士サファリパーク',
          type: 'destination',
          isMain: true,
          time: '10:00',
          endTime: '14:00',
          transport: 'taxi',
          lat: 35.2352,
          lng: 138.8926,
          memo: '',
          sortOrder: 1,
        },
        {
          id: 'spot-3-3',
          dayId: 'day-3',
          name: '五味八珍',
          type: 'food',
          isMain: true,
          time: '14:30',
          transport: 'taxi',
          lat: 35.1100,
          lng: 138.9400,
          memo: '浜松餃子の有名チェーン',
          sortOrder: 2,
        },
        {
          id: 'spot-3-4',
          dayId: 'day-3',
          name: 'メトロポリタン丸の内ホテル',
          type: 'hotel',
          isMain: false,
          time: '18:00',
          transport: 'subway',
          lat: 35.6812,
          lng: 139.7671,
          memo: 'チェックイン',
          sortOrder: 3,
        },
      ],
    },
    // ─── Day 4：築地 ───
    {
      id: 'day-4',
      tripId: 'trip-family-tokyo-2026',
      dayNum: 4,
      headline: '築地',
      spots: [
        {
          id: 'spot-4-1',
          dayId: 'day-4',
          name: '築地',
          type: 'destination',
          isMain: true,
          time: '09:00',
          endTime: '12:00',
          transport: 'subway',
          lat: 35.6654,
          lng: 139.7707,
          memo: '築地場外市場で食べ歩き',
          sortOrder: 0,
        },
        {
          id: 'spot-4-2',
          dayId: 'day-4',
          name: '羽田空港',
          type: 'transit',
          isMain: false,
          time: '14:00',
          transport: 'subway',
          lat: 35.5494,
          lng: 139.7798,
          memo: '帰路',
          sortOrder: 1,
        },
      ],
    },
  ],
};
